name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: make build-linux
