name: Release

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        env
        make build-all
        ./.github/build/build-rpm.sh
        ./.github/build/build-deb.sh
        ls -l ./_release
#    - uses: softprops/action-gh-release@v1
#      if: startsWith(github.ref, 'refs/tags/')
#      with:
#        files: _releases/*
#    - run: |
#        ./.github/build/homebrew-tap-publish.sh
#        ./.github/build/docker-publish.sh
