name: Release

on:
  push:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: make release-test
    
